# Generated by Django 5.0.1 on 2024-01-17 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_admin_technoadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryType', models.CharField(max_length=355)),
                ('CategoryTitle', models.CharField(max_length=355)),
                ('CategoryName', models.CharField(max_length=355)),
                ('CategoryIcon', models.CharField(max_length=355)),
            ],
        ),
    ]
