# Generated by Django 5.0.1 on 2024-01-24 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_newcategory_delete_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('product_count', models.IntegerField()),
                ('sku', models.CharField(max_length=50)),
                ('stock_status', models.CharField(choices=[('0', 'In stock'), ('1', 'Out of stock')], max_length=10)),
                ('regular_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('photo1', models.ImageField(upload_to='product_photos/')),
                ('photo2', models.ImageField(upload_to='product_photos/')),
                ('photo3', models.ImageField(upload_to='product_photos/')),
                ('photo4', models.ImageField(upload_to='product_photos/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.newcategory')),
            ],
        ),
    ]
