# Generated by Django 5.0.1 on 2024-01-24 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
