# Generated by Django 5.0.1 on 2024-01-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('product_count', models.IntegerField()),
                ('sku', models.CharField(max_length=255)),
                ('stock_status', models.CharField(choices=[('0', 'In stock'), ('1', 'Out of stock')], max_length=255)),
                ('regular_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('parent_category', models.CharField(max_length=255)),
                ('sub_category', models.CharField(max_length=255)),
                ('sub_sub_category', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('primary_photo', models.ImageField(upload_to='product_photos/')),
                ('photo1', models.ImageField(blank=True, null=True, upload_to='product_photos/')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='product_photos/')),
                ('photo3', models.ImageField(blank=True, null=True, upload_to='product_photos/')),
                ('photo4', models.ImageField(blank=True, null=True, upload_to='product_photos/')),
                ('tags', models.ManyToManyField(to='main.tag')),
            ],
        ),
    ]
