# Generated by Django 5.0.1 on 2024-01-26 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_tag_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newcategory',
            name='status',
        ),
    ]
